<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_cart' => [[], ['_controller' => 'App\\Controller\\CartController::index'], [], [['text', '/api/cart']], [], [], []],
    'add_product_to_cart' => [['productId'], ['_controller' => 'App\\Controller\\CartController::addProductToCart'], [], [['variable', '/', '[^/]++', 'productId', true], ['text', '/api/cart/add']], [], [], []],
    'remove_product_from_cart' => [['cartItemId'], ['_controller' => 'App\\Controller\\CartController::removeProductFromCart'], [], [['variable', '/', '[^/]++', 'cartItemId', true], ['text', '/api/cart/remove']], [], [], []],
    'get_cart' => [[], ['_controller' => 'App\\Controller\\CartController::getCart'], [], [['text', '/api/cart']], [], [], []],
    'validate_cart' => [[], ['_controller' => 'App\\Controller\\CartController::validateCart'], [], [['text', '/api/cart/validate']], [], [], []],
    'get_orders' => [[], ['_controller' => 'App\\Controller\\OrderController::getOrders'], [], [['text', '/api/orders']], [], [], []],
    'get_order' => [['id'], ['_controller' => 'App\\Controller\\OrderController::getOrder'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/orders']], [], [], []],
    'get_products' => [[], ['_controller' => 'App\\Controller\\ProductController::getProducts'], [], [['text', '/api/products']], [], [], []],
    'get_product' => [['id'], ['_controller' => 'App\\Controller\\ProductController::getProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'add_product' => [[], ['_controller' => 'App\\Controller\\ProductController::addProduct'], [], [['text', '/api/products']], [], [], []],
    'update_product' => [['id'], ['_controller' => 'App\\Controller\\ProductController::updateProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'delete_product' => [['id'], ['_controller' => 'App\\Controller\\ProductController::deleteProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'user_register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/api/register']], [], [], []],
    'user_login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/api/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\UserController::logout'], [], [['text', '/api/logout']], [], [], []],
    'user_get_current' => [[], ['_controller' => 'App\\Controller\\UserController::getCurrentUser'], [], [['text', '/api/user']], [], [], []],
    'user_update' => [[], ['_controller' => 'App\\Controller\\UserController::updateUser'], [], [['text', '/api/user']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
